function [srf, srf_th, v_fld, vth_fld] = ...
               draw_surf(ax_h, ax_v, Nx, dx, Ny, dy,...
                         u, v, h, zbounds, h_th)
    %[Xu, Yu] = meshgrid((0:1:Nx) * dx, ((1:1:Ny) - 1/2) * dy);
    %[Xv, Yv] = meshgrid(((1:1:Nx) - 1/2) * dx, (0:1:Ny) * dy);
    [Xh, Yh] = meshgrid(((1:1:Nx) - 1/2) * dx, ((1:1:Ny) - 1/2) * dy);
    
    zbounds = [-zbounds, zbounds];
    srf = surf(ax_h, Xh, Yh, h, ...
               'EdgeColor', 'interp', 'FaceColor', 'interp');
    if(isempty(h_th))
        srf_th = [];
    else
        srf_th = surf(ax_h, Xh, Yh, h_th, 'DisplayName', 'theory',...
            'EdgeColor', 'interp', 'FaceColor', 'interp', ...
            'FaceAlpha', 0.5, 'EdgeAlpha', 0.5);        
    end
    zlim(ax_h, zbounds);
    caxis(ax_h, zbounds);
    
    v_fld = quiver(ax_v, Xh, Yh, ...
                   (u(:, 1:(end-1)) + u(:, 2:end))/2,...
                   (v(1:(end-1), :) + v(2:end, :))/2,...
                   'Color', getMyColor(2));
end
