function [srf, v_fld, srf_dh, srf_th, vth_fld] = ...
               draw_surf(figs, Nx, dx, Ny, dy,...
                         u, v, h, zbounds, h_th)
    %[Xu, Yu] = meshgrid((0:1:Nx) * dx, ((1:1:Ny) - 1/2) * dy);
    %[Xv, Yv] = meshgrid(((1:1:Nx) - 1/2) * dx, (0:1:Ny) * dy);
    [Xh, Yh] = meshgrid(((1:1:Nx) - 1/2) * dx, ((1:1:Ny) - 1/2) * dy);
    
    zbounds = [-zbounds, zbounds];
    srf = surf(figs.fig_h.ax, Xh, Yh, h, ...
               'EdgeColor', 'interp', 'FaceColor', 'interp');
    if(isempty(h_th))
        srf_th = [];
        srf_dh = [];
        vth_fld = [];
    else
        srf_th = surf(figs.fig_h.ax, Xh, Yh, h_th, 'DisplayName', 'theory',...
            'EdgeColor', 'interp', 'FaceColor', 'interp', ...
            'FaceAlpha', 0.5, 'EdgeAlpha', 0.5);        
        
        srf_dh = surf(figs.fig_dh.ax, Xh, Yh, abs(h - h_th),...
            'EdgeColor', 'interp', 'FaceColor', 'interp');                
        
        vth_fld = [];
        %vth_fld = quiver(figs.fig_v.ax, Xh, Yh, ...
        %               (u(:, 1:(end-1)) + u(:, 2:end))/2,...
        %               (v(1:(end-1), :) + v(2:end, :))/2,...
        %               'Color', getMyColor(2));        
    end
    zlim(figs.fig_h.ax, zbounds);
    caxis(figs.fig_h.ax, zbounds);
    
    v_fld = quiver(figs.fig_v.ax, Xh, Yh, ...
                   (u(:, 1:(end-1)) + u(:, 2:end))/2,...
                   (v(1:(end-1), :) + v(2:end, :))/2,...
                   'Color', getMyColor(2));
end
