function [u_curr, v_curr, h_curr] = ...
             step_RK4(derivative_fun, g, H,...
                        u_curr, v_curr, h_curr, dx, dy, dt)
                    
    [dh1, du1, dv1] = ...
        derivative_fun(g, H,...
                       h_curr,...
                       u_curr,...
                       v_curr,...
                       dx, dy);
    
    [dh2, du2, dv2] = ...
        derivative_fun(g, H, ...
                       h_curr + dh1 * (dt/2),...
                       u_curr + du1 * (dt/2),...
                       v_curr + dv1 * (dt/2),...
                       dx, dy);    
                   
    [dh3, du3, dv3] = ...
        derivative_fun(g, H, ...
                       h_curr + dh2 * (dt/2),...
                       u_curr + du2 * (dt/2),...
                       v_curr + dv2 * (dt/2),...
                       dx, dy);    
                   
    [dh4, du4, dv4] = ...
        derivative_fun(g, H, ...
                       h_curr + dh3 * (dt),...
                       u_curr + du3 * (dt),...
                       v_curr + dv3 * (dt),...
                       dx, dy);                       
    
    h_curr = h_curr + (dh1 + dh2*2 + dh3*2 + dh4) * (dt/6);
    u_curr = u_curr + (du1 + du2*2 + du3*2 + du4) * (dt/6);
    v_curr = v_curr + (dv1 + dv2*2 + dv3*2 + dv4) * (dt/6);
end